framework:
  - ./*

base:
  - openmaqs-base/*
  - openmaqs-base/**/*

appium:
  - openmaqs-appium/*
  - openmaqs-appium/**/*

selenium:
  - openmaqs-selenium/*
  - openmaqs-selenium/**/*

webservices:
  - openmaqs-webservices/*
  - openmaqs-webservices/**/*

utilities:
  - openmaqs-utilities/*
  - openmaqs-utilities/**/*

database:
  - openmaqs-database/*
  - openmaqs-database/**/*

devops:
  - .dependabot/*
  - .github/*
  - .github/**/*
 
accessibility:
  - openmaqs-accessibility/*
  - openmaqs-accessibility/**/*

playwright:
  - openmaqs-playwright/*
  - openmaqs-playwright/**/*
